
#The general configuration for this mod
[general]
	#If set to true Shields added by other mods block 100% of the incomming damage, if set to false the will block the amount set in defaultDamageReduction.
	#Default: true
	customShieldMaxReduction = true
	#The portion of the incomming damage Vanilla Shields block in percent.
	#Default: 75
	defaultDamageReduction = 64
	#The portion of the incomming damage Iron Shields block in percent.
	#Default: 90
	ironDamageReduction = 70
	#The portion of the incomming damage Gold Shields block in percent.
	#Default: 85
	goldDamageReduction = 60
	#The portion of the incomming damage Diamond Shields block in percent.
	#Default: 98
	diamondDamageReduction = 80
	#The portion of the incomming damage Netherite Shields block in percent.
	#Default: 100
	netheriteDamageReduction = 90
	#The durability of the Iron Shield.
	#Default: 920
	ironDurability = 920
	#The durability of the Gold Shield.
	#Default: 130
	goldDurability = 210
	#The durability of the Diamond Shield.
	#Default: 4600
	diamondDurability = 4600
	#The durability of the Netherite Shield.
	#Default: 6300
	netheriteDurability = 6300
	#Allows the Thorns enchantment to by applied to Shields
	#Default: true
	thornsOnShields = true
	#Enables modified damage reduction values for shields.
	#Default: true
	enableDamageReduction = true

