#Fire damage duration for direct (main hand) hits.
#Range: 1 ~ 8
directHitDuration = 4
#Fire damage duration for indirect (off hand + tool) hits.
#Range: 1 ~ 8
indirectHitDuration = 2
#List of tools that allow for an indirect hit when a torch is being held in the off hand.
#Leave empty to disable indirect hits.
#Insert either item categories or specific item IDs.
indirectHitToolList = ["sword", "axe", "pickaxe", "shovel", "hoe"]
#List of item ids that should be considered as a Torch.
moddedTorchList = ["torchmaster:megatorch"]
#List of item ids that should be considered as a Soul Torch.
moddedSoulTorchList = []
#Whether torches should break upon use.
"consume torch" = false
#Whether to break the torch upon use even if no fire was set.
#Effective only if [fire chance] and [consume torch] are set different from default.
"consume without fire" = false
#Chance (in percentage) for torches to set targets on fire.
#Range: 1 ~ 100
"fire chance" = 100

