
[world_gen]
	#Config to toggle the generation of arms in snow biomes
	arms = true
	#Configure whether the mods ores spawn. This MAY require a restart when changed.
	genOres = false
	#Configure whether Graveyard Structures spawn. This will require a restart when changed.
	genGraveyard = false
	#Configure whether Catacombs Structures spawn. This will require a restart when changed.
	genCatacombs = false

[spawn]
	#The minimum amount of 'Weeping Angels' that spawn at each spawn attempt
	#Range: 1 ~ 100
	minCount = 1
	#The maximum amount of 'Weeping Angels' that spawn at each spawn attempt
	#Range: 1 ~ 100
	maxCount = 1
	#The weight of spawn in relation to other mods 'Weeping Angels' will spawn in. Less than 100 = Rarer
	#Range: > 1
	spawn_weight = 2
	#'Weeping Angel' spawn classification
	#Allowed Values: MONSTER, CREATURE, AMBIENT, WATER_CREATURE, WATER_AMBIENT, MISC, EITD_EYES
	spawnType = "MONSTER"
	#Note: A list of biomes where angels should spawn.
	spawnBiomes = ["minecraft:ocean", "minecraft:plains", "minecraft:desert", "minecraft:mountains", "minecraft:forest", "minecraft:taiga", "minecraft:swamp", "minecraft:river", "minecraft:nether_wastes", "minecraft:the_end", "minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:mushroom_fields", "minecraft:mushroom_field_shore", "minecraft:beach", "minecraft:desert_hills", "minecraft:wooded_hills", "minecraft:taiga_hills", "minecraft:mountain_edge", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge", "minecraft:deep_ocean", "minecraft:stone_shore", "minecraft:snowy_beach", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:badlands", "minecraft:wooded_badlands_plateau", "minecraft:badlands_plateau", "minecraft:small_end_islands", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:end_barrens", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "outer_end:azure_forest", "outer_end:crystal_crag", "graveyard:haunted_forest", "graveyard:haunted_lakes", "graveyard:eroded_haunted_forest", "endergetic:poise_forest", "appliedenergistics:spatial_storage", "minecraft:the_void", "minecraft:sunflower_plains", "minecraft:desert_lakes", "minecraft:gravelly_mountains", "minecraft:flower_forest", "minecraft:taiga_mountains", "minecraft:swamp_hills", "minecraft:ice_spikes", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest_hills", "minecraft:snowy_taiga_mountains", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "minecraft:eroded_badlands", "minecraft:modified_wooded_badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "minecraft:soul_sand_valley", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:basalt_deltas", "aoa3:abyssal_plains", "aoa3:asteroid_belt", "aoa3:barren_grounds", "witherstormmod:bowels", "aoa3:candy_hills", "aoa3:cavern_depths", "aoa3:celevian_highlands", "aoa3:coral_fields", "aoa3:creepoid_forest", "aoa3:crystevian_caverns", "aoa3:dustopian_forest", "aoa3:floral_islands", "aoa3:fungal_caverns", "aoa3:greckon_mountains", "aoa3:haven", "aoa3:iromine", "aoa3:lelyetian_plains", "aoa3:nowhere", "aoa3:precasian_tall_forest", "aoa3:runic_cliffs", "aoa3:shyre_remnants", "aoa3:vox_wastes"]

[angel]
	#Damage Type For Angels
	#Allowed Values: NOTHING, ANY_PICKAXE_AND_GENERATOR_ONLY, ANY_PICKAXE_ONLY, DIAMOND_AND_ABOVE_PICKAXE_ONLY, GENERATOR_ONLY, EVERYTHING
	damageType = "ANY_PICKAXE_AND_GENERATOR_ONLY"
	#Non-child angels play scraping sounds when moving, this toggles that
	playScrapeSound = true
	#Toggle seen sounds
	playSeenSounds = true
	#The damage dealt by an angel
	#Range: 1.0 ~ 1.7976931348623157E308
	damage = 10.0
	#XP gained from angels
	#Range: > 1
	xpGained = 50
	#If this is enabled, the timey wimey detector can blow up chickens when in use randomly
	chickenGoboom = true
	#If this is enabled, baby angels will blow out light items from the players hand
	torchBlowOut = true
	#if enabled, angels will freeze when they see one another. (Impacts performance a bit)
	freezeOnAngel = true
	#Determines the range the angels will look for players within, personally, I'd stay under 100
	#Range: 1 ~ 100
	stalkRange = 65
	#Determines the angels move speed
	#Range: 0.1 ~ 1.7976931348623157E308
	angelMovementSpeed = 0.2
	#If this is enabled, angels will break blocks (If gamerules allow) - !!!! BLOCK BLACKLISTING: You may be looking for a config option in order to stop certain blocks from being broken. You can do this with a datapack using weeping_angels:angel_proof
	blockBreaking = false
	#The maximum range a angel can break blocks within
	#Range: 1 ~ 120
	blockBreakRange = 15

[teleport]
	#Teleport Type - STRUCTURES: Teleports you to Structures Only - DONT: No Teleporting, only damage - RANDOM: Anywhere
	#Allowed Values: STRUCTURES, RANDOM_PLACE, DONT
	teleportType = "RANDOM_PLACE"
	#Note: This a list of dimensions that angels should NOT teleport you to.
	notAllowedDimensions = ["neverise:witherstorm", "aoa3:nowhere", "witherstormmod:bowels", "minecraft:the_end"]
	#just teleport. no damage.
	justTeleport = false
	#The maximum range a user can be teleported by the Angels
	#Range: > 1
	teleportRange = 300
	#If this is enabled, angel teleporting can also tp the player to other dimensions
	angelDimTeleport = true
	#Should Angels target creative players?
	aggroCreative = false

[block]
	#This config option toggles whether angels can spawn from Statues/Plinths when they receive a redstone signal
	spawnFromBlocks = false

[misc]
	#Toggle whether santa hats are shown at Xmas
	showSantaHatsAtXmas = true
	#Toggle certain angel models (Only applies to Entity)
	allowedAngelTypes = ["DISASTER_MC", "DOCTOR", "ED", "ED_ANGEL_CHILD", "A_DIZZLE", "DYING", "VILLAGER", "VIO_1", "VIO_2", "SPARE_TIME"]
	#Toggle certain angel variants (Only applies to Entity)
	allowedVariants = ["weeping_angels:gold", "weeping_angels:diamond", "weeping_angels:iron", "weeping_angels:mossy", "weeping_angels:normal", "weeping_angels:basalt", "weeping_angels:rusted", "weeping_angels:rusted_no_arm", "weeping_angels:rusted_no_wing", "weeping_angels:rusted_no_head", "weeping_angels:dirt", "weeping_angels:emerald", "weeping_angels:copper", "weeping_angels:lapis_lazuli", "weeping_angels:quartz"]

