
#Durability settings
[durability]
	#Range: 1 ~ 10000
	durability_oak = 64
	#Range: 1 ~ 10000
	durability_acacia = 64
	#Range: 1 ~ 10000
	durability_birch = 64
	#Range: 1 ~ 10000
	durability_jungle = 64
	#Range: 1 ~ 10000
	durability_spruce = 64
	#Range: 1 ~ 10000
	durability_dark_oak = 64
	#Range: 1 ~ 10000
	durability_charred = 64

